name: My First GitHub Actions Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello Message
        run: echo "Hello from GitHub Actions!"

      - name: Check Node Version
        run: node --version
      - name: multiple files list
        run: ls ${{ github.workspace }}
